[package]
name = "native_app"
version = "0.4.3"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

futures       = { version = "0.3.4", default-features = false, features = ["executor"] }
bytemuck      = "1.7.2"
egregoria     = { path = "../egregoria" }
geom          = { path = "../geom" }
wgpu_engine   = { path = "../wgpu_engine" }
common        = { path = "../common" }
networking    = { path = "../networking", optional=true }
goria_version = { path = "../goria_version" }
imgui-inspect = { path = "../imgui-inspect" }
imgui-inspect-derive = { path = "../imgui-inspect-derive" }
imgui-wgpu    = { git = "https://github.com/Yatekii/imgui-wgpu-rs" }
imgui-winit-support = { version = "0.8.2", default-features = false, features=["winit-26"] }
map_model     = { path = "../map_model" }
flat_spatial  = { path = "../flat_spatial" }
log           = { version = "0.4.11", features=["max_level_debug", "release_max_level_info"] }
inline_tweak  = "1.0.6"
imgui         = "0.8"
hecs          = "0.7.6"
resources     = "1.1.0"
ordered-float = { version = "2.7.0", default-features = false }
serde         = "1.0"
oddio         = "0.5.0"
cpal          = "0.13.5"
lewton        = "0.10.2"
slotmap       = { version = "1.0.2", default-features = false }
winit         = "0.26.1"
paste         = "1.0.4"
atomic_refcell = "0.1.6"
rayon         = "1.5.3"
profiling     = "1.0.1"
include_dir   = "0.7.2"

[target.'cfg(target_arch = "wasm32")'.dependencies.imgui]
version = "0.8"
features = ["wasm"]

[features]
default = []
enable_profile = ["profiling/profile-with-tracy"]
multiplayer = ["networking"]