[package]
name = "wgpu_engine"
version = "0.1.0"
authors = ["Paris DOUADY <paris.douady@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geom      = { path = "../geom" }
common    = { path = "../common" }
wgpu      = "0.7.0"
bytemuck  = "1.4.1"
mint      = "0.5.6"
image     = { version = "0.23.4", default-features = false, features = ["png"] }
log       = "0.4.11"
raw-window-handle = "0.3.3"
naga      = { version = "0.3.2", features = ["glsl-in", "spv-out"], optional = true}
tobj      = "2.0.4"

[features]
default = []
spirv_naga = ["naga"]